In [3]:
import pandas as pd

In [5]:
ratings = pd.read_csv("/home/sreenandump/Project/semantic-movie-recommender-two-tower/ml/data/raw/ml-latest-small/ratings.csv")
movies = pd.read_csv("/home/sreenandump/Project/semantic-movie-recommender-two-tower/ml/data/raw/ml-latest-small/movies.csv")

In [7]:
ratings.head(10)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [8]:
movies.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [13]:
movie_stats = ratings.groupby("movieId").agg({
    "rating": ["mean", "count"]
})
movie_stats.columns = ["avg_rating", "rating_count"]
movie_stats.head(10)

         avg_rating  rating_count
movieId
1          3.920930           215
2          3.431818           110
3          3.259615            52
4          2.357143             7
5          3.071429            49
6          3.946078           102
7          3.185185            54
8          2.875000             8
9          3.125000            16
10         3.496212           132

In [14]:
popular = movie_stats.sort_values(
    by=["avg_rating", "rating_count"],
    ascending=False
)
popular.head(10)

         avg_rating  rating_count
movieId
53              5.0             2
99              5.0             2
1151            5.0             2
3473            5.0             2
6442            5.0             2
6818            5.0             2
78836           5.0             2
148             5.0             1
467             5.0             1
495             5.0             1

In [15]:
popular = popular.merge(
    movies,
    on="movieId"
)
popular.head(10)

,movieId,avg_rating,rating_count,title,genres
0,53,5.0,2,Lamerica (1994),Adventure|Drama
1,99,5.0,2,Heidi Fleiss: Hollywood Madam (1995),Documentary
2,1151,5.0,2,Lesson Faust (1994),Animation|Comedy|Drama|Fantasy
3,3473,5.0,2,Jonah Who Will Be 25 in the Year 2000 (Jonas q...,Comedy
4,6442,5.0,2,Belle époque (1992),Comedy|Romance
5,6818,5.0,2,Come and See (Idi i smotri) (1985),Drama|War
6,78836,5.0,2,Enter the Void (2009),Drama
7,148,5.0,1,"Awfully Big Adventure, An (1995)",Drama
8,467,5.0,1,Live Nude Girls (1995),Comedy
9,495,5.0,1,In the Realm of the Senses (Ai no corrida) (1976),Drama

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
user_movie_matrix = ratings.pivot_table(
    index = "userId",
    columns = "movieId",
    values = "rating"
)

user_movie_matrix = user_movie_matrix.fillna(0)
user_movie_matrix.head(10)
# movie_similarity = cosine_similarity(user_movie_matrix.T)

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,4.0,5.0,3.0,5.0,4.0,4.0,3.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0